version: '2'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build: .
    ports:
      - '5555:5555'
    volumes:
      - .:/usr/src/app
      # prevents host/container contamination
      - /usr/src/app/node_modules
    env_file: .env
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
    command: npm run dev
